name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker rm -f flask-container || true
          docker rmi flask-app || true
          git clone https://github.com/Saifudheenpv/flask-docker-deploy || true
          cd flask-docker-deploy
          docker build -t flask-app .
          docker run -d -p 5000:5000 --name flask-container flask-app 